FROM mcr.microsoft.com/dotnet/runtime:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["SensorReaderService/SensorReaderService.csproj", "SensorReaderService/"]
RUN dotnet restore "SensorReaderService/SensorReaderService.csproj"
COPY . .
WORKDIR "/src/SensorReaderService"
RUN dotnet build "SensorReaderService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SensorReaderService.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SensorReaderService.dll"]
